bicycle_model:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  rear_wheel_joint_position_controller:
    type: effort_controllers/JointEffortController
    joint: rear_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_wheel_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
